version: 2

models:
  - name: int_crypto_features
    description: "Intermediate features for each crypto asset, derived from stg_all_crypto"
    columns:
      - name: asset
        description: "The crypto asset identifier (e.g., BTC-USD)"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: close_price
        description: "Closing price of the asset on this date"
        tests:
          - not_null
      - name: daily_return
        description: "Daily return for the asset"
        tests:
          - not_null

  - name: int_daily_asset_metrics
    description: "Daily metrics per crypto asset, including moving averages and volatility"
    columns:
      - name: asset
        description: "Crypto asset identifier"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: close_price
        description: "Closing price"
        tests:
          - not_null
      - name: daily_return
        description: "Daily return for the asset"
        tests:
          - not_null
      - name: ma_7
        description: "7-day moving average of close_price"
      - name: ma_30
        description: "30-day moving average of close_price"
      - name: volatility_7
        description: "7-day rolling volatility (stddev of daily_return)"
